/**
 * Deployer Unit Tests
 * Tests manifest handling, config generation, and deployment status
 */

import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest'
import { mkdirSync, writeFileSync, existsSync, rmSync, readFileSync } from 'fs'
import { join } from 'path'
import {
  readManifest,
  isDxvkInstalled,
  getInstalledVersion,
  checkIntegrity,
  generateConfigFile
} from '../deployer'
import type { DeploymentManifest, DxvkConfig } from '../../shared/types'

const FIXTURES_DIR = join(__dirname, 'fixtures', 'deployer')
const GAME_DIR = join(FIXTURES_DIR, 'test-game')

describe('Deployer', () => {
  beforeAll(() => {
    mkdirSync(GAME_DIR, { recursive: true })
  })

  afterAll(() => {
    if (existsSync(FIXTURES_DIR)) {
      rmSync(FIXTURES_DIR, { recursive: true, force: true })
    }
  })

  beforeEach(() => {
    // Clean up any manifest from previous tests
    const manifestPath = join(GAME_DIR, 'dxvk_studio_manifest.json')
    if (existsSync(manifestPath)) {
      rmSync(manifestPath)
    }
  })

  describe('readManifest', () => {
    it('should return null for game without manifest', () => {
      const manifest = readManifest(GAME_DIR)
      expect(manifest).toBeNull()
    })

    it('should read valid manifest', () => {
      const testManifest: DeploymentManifest = {
        gameId: 'test-game-123',
        engineVersion: '2.7.1',
        engineFork: 'official',
        architecture: '64',
        installedAt: new Date().toISOString(),
        dlls: [
          { name: 'd3d11.dll', hash: 'abc123' },
          { name: 'dxgi.dll', hash: 'def456' }
        ]
      }

      writeFileSync(
        join(GAME_DIR, 'dxvk_studio_manifest.json'),
        JSON.stringify(testManifest)
      )

      const manifest = readManifest(GAME_DIR)

      expect(manifest).not.toBeNull()
      expect(manifest?.gameId).toBe('test-game-123')
      expect(manifest?.engineVersion).toBe('2.7.1')
      expect(manifest?.dlls.length).toBe(2)
    })

    it('should return null for invalid JSON', () => {
      writeFileSync(
        join(GAME_DIR, 'dxvk_studio_manifest.json'),
        'not valid json {'
      )

      const manifest = readManifest(GAME_DIR)
      expect(manifest).toBeNull()
    })
  })

  describe('isDxvkInstalled', () => {
    it('should return false for game without manifest', () => {
      expect(isDxvkInstalled(GAME_DIR)).toBe(false)
    })

    it('should return true for game with manifest', () => {
      mkdirSync(GAME_DIR, { recursive: true })
      writeFileSync(
        join(GAME_DIR, 'dxvk_studio_manifest.json'),
        JSON.stringify({ gameId: 'test', engineVersion: '1.0', engineFork: 'official', architecture: '64', installedAt: '', dlls: [] })
      )

      expect(isDxvkInstalled(GAME_DIR)).toBe(true)
    })
  })

  describe('getInstalledVersion', () => {
    it('should return null for game without DXVK', () => {
      const version = getInstalledVersion(GAME_DIR)
      expect(version).toBeNull()
    })

    it('should return version and fork for installed game', () => {
      mkdirSync(GAME_DIR, { recursive: true })
      writeFileSync(
        join(GAME_DIR, 'dxvk_studio_manifest.json'),
        JSON.stringify({
          gameId: 'test',
          engineVersion: '2.7.1',
          engineFork: 'gplasync',
          architecture: '64',
          installedAt: '',
          dlls: []
        })
      )

      const result = getInstalledVersion(GAME_DIR)

      expect(result).not.toBeNull()
      expect(result?.version).toBe('2.7.1')
      expect(result?.fork).toBe('gplasync')
    })
  })

  describe('checkIntegrity', () => {
    it('should return not_installed for game without manifest', () => {
      expect(checkIntegrity(GAME_DIR)).toBe('not_installed')
    })
  })

  describe('generateConfigFile', () => {
    it('should generate config with all options', () => {
      const config: DxvkConfig = {
        enableAsync: true,
        numCompilerThreads: 4,
        maxFrameLatency: 1,
        enableHDR: false,
        logLevel: 'warn'
      }

      const content = generateConfigFile(config)

      expect(content).toContain('dxvk.enableAsync = true')
      expect(content).toContain('dxvk.numCompilerThreads = 4')
      expect(content).toContain('dxgi.maxFrameLatency = 1')
      expect(content).toContain('dxgi.enableHDR = false')
      expect(content).toContain('DXVK_LOG_LEVEL = warn')
    })

    it('should include header comments', () => {
      const content = generateConfigFile({})

      expect(content).toContain('# DXVK Configuration')
      expect(content).toContain('# Generated by DXVK Studio')
    })

    it('should handle empty config', () => {
      const content = generateConfigFile({})

      // Should only have header comments
      const lines = content.split('\n').filter(l => !l.startsWith('#') && l.trim() !== '')
      expect(lines.length).toBe(0)
    })

    it('should format HUD options correctly', () => {
      const config: DxvkConfig = {
        hud: ['fps', 'gpuload', 'memory'],
        hudScale: 1.5
      }

      const content = generateConfigFile(config)
      expect(content).toContain('DXVK_HUD = fps,gpuload,memory,scale=1.5')
    })

    it('should format HUD scale only', () => {
      const config: DxvkConfig = {
        hudScale: 0.75
      }

      const content = generateConfigFile(config)
      expect(content).toContain('DXVK_HUD = scale=0.75')
    })

    it('should handle custom vendor/device IDs', () => {
      const config: DxvkConfig = {
        customVendorId: '0x10de',
        customDeviceId: '0x2206'
      }

      const content = generateConfigFile(config)
      expect(content).toContain('dxgi.customVendorId = 0x10de')
      expect(content).toContain('dxgi.customDeviceId = 0x2206')
    })
  })
})
